//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvisioningPrototype {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProvisioningPrototype.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AltText.
        /// </summary>
        internal static string AltTextAttribute {
            get {
                return ResourceManager.GetString("AltTextAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices.
        /// </summary>
        internal static string ChoicesGroup {
            get {
                return ResourceManager.GetString("ChoicesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentName.
        /// </summary>
        internal static string ComponentNameAttribute {
            get {
                return ResourceManager.GetString("ComponentNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentValueList.
        /// </summary>
        internal static string ComponentValueListAttribute {
            get {
                return ResourceManager.GetString("ComponentValueListAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*%%ContentBackgroundColor*/.
        /// </summary>
        internal static string ContentBackgroundColorVariable {
            get {
                return ResourceManager.GetString("ContentBackgroundColorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253Ep_[REPLACE_1]%253C%252Fc%253E%253Cc%253E-1%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E1%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EToolTip%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253ETypeName%253C%252Fc%253E%253Cc%253EVisionCritical.PanelPlus.SerialSequence%252C%2520VisionCritical.PanelPlus%252C%2520Version%253D4.3.4227.37933%252C%2520Culture%253Dneutral%252C%2520Pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ctl10_wT_wTt_Data {
            get {
                return ResourceManager.GetString("ctl10_wT_wTt_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EApplicationPath%253C%252Fc%253E%253Cc%253E%252FAdmin%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EChildSelectedHoverNodeCssClass%253C%252Fc%253E%253Cc%253EWorkFlowTree_ChildSelectedHoverNode%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EChildSelectedHoverNodeRowCssClass%253C%252Fc%253E%253Cc%253EWorkFlowTree_ChildSelectedHoverNodeRow%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ctl10_wT_wTt_Properties {
            get {
                return ResourceManager.GetString("ctl10_wT_wTt_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content.
        /// </summary>
        internal static string DataDirectoryPath {
            get {
                return ResourceManager.GetString("DataDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultAttribute {
            get {
                return ResourceManager.GetString("DefaultAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253Ep0%253C%252Fc%253E%253Cc%253E-1%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EText%253C%252Fc%253E%253Cc%253EQuestions%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EContentCallbackUrl%253C%252Fc%253E%253Cc%253Ehttp%253A%252F%252F[HOST]%252FAdmin%252FTreeXmlLoadOnDemand.aspx%253Fpipes%253Dquestions%2526cb%253DHandlePipeClick%28% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string e_pipesDiv_pipesTree_Data {
            get {
                return ResourceManager.GetString("e_pipesDiv_pipesTree_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EApplicationPath%253C%252Fc%253E%253Cc%253E%252FAdmin%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EChildSelectedHoverNodeCssClass%253C%252Fc%253E%253Cc%253EWorkFlowTree_ChildSelectedHoverNode%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EChildSelectedHoverNodeRowCssClass%253C%252Fc%253E%253Cc%253EWorkFlowTree_ChildSelectedHoverNodeRow%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string e_pipesDiv_pipesTree_Properties {
            get {
                return ResourceManager.GetString("e_pipesDiv_pipesTree_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFolder.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenericPortalSkin\GenericPortalSkin.zip.
        /// </summary>
        internal static string GenericPortalSkinZipPath {
            get {
                return ResourceManager.GetString("GenericPortalSkinZipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenericSurveySkin\GenericSurveySkin.zip.
        /// </summary>
        internal static string GenericSurveySkinZipPath {
            get {
                return ResourceManager.GetString("GenericSurveySkinZipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string GroupingAttribute {
            get {
                return ResourceManager.GetString("GroupingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupLabel.
        /// </summary>
        internal static string GroupLabelAttribute {
            get {
                return ResourceManager.GetString("GroupLabelAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string ImagesGroup {
            get {
                return ResourceManager.GetString("ImagesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253Ep_MyLibrary%253C%252Fc%253E%253Cc%253E-1%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EID%253C%252Fc%253E%253Cc%253EMyLibrary%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EText%253C%252Fc%253E%253Cc%253EMy%2520Library%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EValue%253C%252Fc%253E%253Cc%253 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LibraryDiv_lT_Data {
            get {
                return ResourceManager.GetString("LibraryDiv_lT_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EApplicationPath%253C%252Fc%253E%253Cc%253E%252FAdmin%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EChildSelectedHoverNodeCssClass%253C%252Fc%253E%253Cc%253EWorkflowTree_ChildSelectedHoverNode%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EChildSelectedHoverNodeRowCssClass%253C%252Fc%253E%253Cc%253EWorkflowTree_ChildSelectedHoverNodeRow%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LibraryDiv_lT_Properties {
            get {
                return ResourceManager.GetString("LibraryDiv_lT_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListGroup {
            get {
                return ResourceManager.GetString("ListGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Content\Skins\Templates.
        /// </summary>
        internal static string LocalTemplatePath {
            get {
                return ResourceManager.GetString("LocalTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Login.png.
        /// </summary>
        internal static string LoginImageFileName {
            get {
                return ResourceManager.GetString("LoginImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\_img\shared\login-image.jpg.
        /// </summary>
        internal static string LogoImageFilePath {
            get {
                return ResourceManager.GetString("LogoImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameAttribute {
            get {
                return ResourceManager.GetString("NameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPortalSkin.zip.
        /// </summary>
        internal static string NewPortalSkinPath {
            get {
                return ResourceManager.GetString("NewPortalSkinPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*%%NewsletterListVisibility*/.
        /// </summary>
        internal static string NewsletterVisibilityVariable {
            get {
                return ResourceManager.GetString("NewsletterVisibilityVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewSurveySkin.zip.
        /// </summary>
        internal static string NewSurveySkinPath {
            get {
                return ResourceManager.GetString("NewSurveySkinPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*%%PageBackgroundColor*/.
        /// </summary>
        internal static string PageBackgroundColorVariable {
            get {
                return ResourceManager.GetString("PageBackgroundColorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\_css\common.css.
        /// </summary>
        internal static string PortalCommonCSSPath {
            get {
                return ResourceManager.GetString("PortalCommonCSSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\_img\shared\header.jpg.
        /// </summary>
        internal static string PortalHeaderImageFilePath {
            get {
                return ResourceManager.GetString("PortalHeaderImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Portal.png.
        /// </summary>
        internal static string PortalImageFileName {
            get {
                return ResourceManager.GetString("PortalImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\_img\shared\.
        /// </summary>
        internal static string PortalImageFilePath {
            get {
                return ResourceManager.GetString("PortalImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\_css\Login.css.
        /// </summary>
        internal static string PortalLoginCSSPath {
            get {
                return ResourceManager.GetString("PortalLoginCSSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\_css\member.css.
        /// </summary>
        internal static string PortalMemberCSSPath {
            get {
                return ResourceManager.GetString("PortalMemberCSSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkin\PortalSkin.zip.
        /// </summary>
        internal static string PortalSkinFileName {
            get {
                return ResourceManager.GetString("PortalSkinFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skin.
        /// </summary>
        internal static string PortalSkinPathParent {
            get {
                return ResourceManager.GetString("PortalSkinPathParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload.
        /// </summary>
        internal static string PortalSkinToUploadPath {
            get {
                return ResourceManager.GetString("PortalSkinToUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortalSkinToUpload\PortalSkin.zip.
        /// </summary>
        internal static string PortalSkinZipToUploadPath {
            get {
                return ResourceManager.GetString("PortalSkinZipToUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/PQs.
        /// </summary>
        internal static string PQsDirectoryPath {
            get {
                return ResourceManager.GetString("PQsDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*%%PrimaryTextColor*/.
        /// </summary>
        internal static string PrimaryTextColorVariable {
            get {
                return ResourceManager.GetString("PrimaryTextColorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyName.
        /// </summary>
        internal static string PropertyNameAttribute {
            get {
                return ResourceManager.GetString("PropertyNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*%%QuickPollVisibility*/.
        /// </summary>
        internal static string QuickPollVisibilityVariable {
            get {
                return ResourceManager.GetString("QuickPollVisibilityVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplacementDirectory.
        /// </summary>
        internal static string ReplacementDirectoryAttribute {
            get {
                return ResourceManager.GetString("ReplacementDirectoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*%%SecondaryTextColor*/.
        /// </summary>
        internal static string SecondaryTextColorVariable {
            get {
                return ResourceManager.GetString("SecondaryTextColorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionTemplates.
        /// </summary>
        internal static string SessionTemplates {
            get {
                return ResourceManager.GetString("SessionTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Skins.
        /// </summary>
        internal static string SkinsDirectoryPath {
            get {
                return ResourceManager.GetString("SkinsDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22State%22%3A%7B%7D%2C%22TabState%22%3A%7B%22sTabs_ctl02%22%3A%7B%22Selected%22%3Atrue%7D%7D%7D.
        /// </summary>
        internal static string sTabs {
            get {
                return ResourceManager.GetString("sTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22State%22%3A%7B%22SelectedIndex%22%3A6%7D%2C%22TabState%22%3A%7B%22sTabs_ctl02%22%3A%7B%22Selected%22%3Afalse%7D%2C%22sTabs_ctl06%22%3A%7B%22Selected%22%3Atrue%7D%7D%7D.
        /// </summary>
        internal static string sTabs_Deploy {
            get {
                return ResourceManager.GetString("sTabs_Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution.
        /// </summary>
        internal static string SubstituionAttribute {
            get {
                return ResourceManager.GetString("SubstituionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Substitutions/Variables.
        /// </summary>
        internal static string SubstitutionVariablesPath {
            get {
                return ResourceManager.GetString("SubstitutionVariablesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SubstitutionXml.xml.
        /// </summary>
        internal static string SubstitutionXmlFileName {
            get {
                return ResourceManager.GetString("SubstitutionXmlFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Substitutions/Groupings.
        /// </summary>
        internal static string SubstitutonGroupsPath {
            get {
                return ResourceManager.GetString("SubstitutonGroupsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveySkinToUpload\images\survey-header.jpg.
        /// </summary>
        internal static string SurveyHeaderImageFilePath {
            get {
                return ResourceManager.GetString("SurveyHeaderImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Survey.png.
        /// </summary>
        internal static string SurveyImageFileName {
            get {
                return ResourceManager.GetString("SurveyImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveySkinToUpload\images\.
        /// </summary>
        internal static string SurveyImageFilePath {
            get {
                return ResourceManager.GetString("SurveyImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveySkinToUpload\css\surveyLayout.css.
        /// </summary>
        internal static string SurveyLayoutCSSPath {
            get {
                return ResourceManager.GetString("SurveyLayoutCSSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveySkin\SurveySkin.zip.
        /// </summary>
        internal static string SurveySkinFileName {
            get {
                return ResourceManager.GetString("SurveySkinFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveySkinToUpload.
        /// </summary>
        internal static string SurveySkinToUploadPath {
            get {
                return ResourceManager.GetString("SurveySkinToUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveySkinToUpload\SurveySkin.zip.
        /// </summary>
        internal static string SurveySkinZipToUploadPath {
            get {
                return ResourceManager.GetString("SurveySkinZipToUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateColors.
        /// </summary>
        internal static string TemplateColorsGroup {
            get {
                return ResourceManager.GetString("TemplateColorsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/Skins/Templates/.
        /// </summary>
        internal static string TemplateImagePath {
            get {
                return ResourceManager.GetString("TemplateImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplatePath {
            get {
                return ResourceManager.GetString("TemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextGroup {
            get {
                return ResourceManager.GetString("TextGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253E31%253C%252Fc%253E%253Cc%253Ep0%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E29%253C%252Fc%253E%253Cc%253E1%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E27%253C%252Fc%253E%253Cc%253Elside.gif%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253E26%253C%252Fc%253E%253Cc%253E22%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string treeToolBar_ItemStorage {
            get {
                return ResourceManager.GetString("treeToolBar_ItemStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %253Cr%253E%253Cc%253E%253Cr%253E%253Cc%253EApplicationPath%253C%252Fc%253E%253Cc%253E%252FAdmin%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EAutoPostBackOnCheckChanged%253C%252Fc%253E%253Cc%253Efalse%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EAutoPostBackOnSelect%253C%252Fc%253E%253Cc%253Efalse%253C%252Fc%253E%253C%252Fr%253E%253C%252Fc%253E%253Cc%253E%253Cr%253E%253Cc%253EClientEvents%253C%252Fc%253E%253Cc%253E%255Bobject%2520Object%2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string treeToolBar_Properties {
            get {
                return ResourceManager.GetString("treeToolBar_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIComponent.
        /// </summary>
        internal static string UIComponentAttribute {
            get {
                return ResourceManager.GetString("UIComponentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIName.
        /// </summary>
        internal static string UiNameAttribute {
            get {
                return ResourceManager.GetString("UiNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Uploads.
        /// </summary>
        internal static string UploadsDirectoryPath {
            get {
                return ResourceManager.GetString("UploadsDirectoryPath", resourceCulture);
            }
        }
    }
}
